name: Pull request workflow

on: pull_request

jobs:
  lint:
    name: Find linting problems in your JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install node_modules
        run: yarn

      - name: Run scripts check
        run: yarn run lint:scripts

      - name: Run styles check
        run: yarn run lint:styles

      - name: Run prettier check
        run: yarn run lint:prettier

  test:
    name: Running unit tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install node_modules
        run: yarn

      - name: Run tests
        run: yarn run test --passWithNoTests
